---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-bdos-io-v1alpha1-bigdatacluster
  failurePolicy: Fail
  name: mbigdatacluster.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bigdataclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-bdos-io-v1alpha1-contextsecret
  failurePolicy: Fail
  name: mcontextsecret.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-bdos-io-v1alpha1-contextsetting
  failurePolicy: Fail
  name: mcontextsetting.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsettings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-bdos-io-v1alpha1-customsecret
  failurePolicy: Fail
  name: mcustomsecret.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-bdos-io-v1alpha1-customsetting
  failurePolicy: Fail
  name: mcustomsetting.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customsettings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-bdos-io-v1alpha1-orgresourcecontrol
  failurePolicy: Fail
  name: morgresourcecontrol.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - orgresourcecontrols
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-bdos-io-v1alpha1-resourcecontrol
  failurePolicy: Fail
  name: mresourcecontrol.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcecontrols
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-bdos-io-v1alpha1-bigdatacluster
  failurePolicy: Fail
  name: vbigdatacluster.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bigdataclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-bdos-io-v1alpha1-contextsecret
  failurePolicy: Fail
  name: vcontextsecret.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-bdos-io-v1alpha1-contextsetting
  failurePolicy: Fail
  name: vcontextsetting.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsettings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-bdos-io-v1alpha1-customsecret
  failurePolicy: Fail
  name: vcustomsecret.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-bdos-io-v1alpha1-customsetting
  failurePolicy: Fail
  name: vcustomsetting.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customsettings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-bdos-io-v1alpha1-orgresourcecontrol
  failurePolicy: Fail
  name: vorgresourcecontrol.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - orgresourcecontrols
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-bdos-io-v1alpha1-resourcecontrol
  failurePolicy: Fail
  name: vresourcecontrol.kb.io
  rules:
  - apiGroups:
    - bdc.bdos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcecontrols
  sideEffects: None
