# permissions for end users to edit contextsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: contextsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpaas-core-operator
    app.kubernetes.io/part-of: bpaas-core-operator
    app.kubernetes.io/managed-by: kustomize
  name: contextsecret-editor-role
rules:
- apiGroups:
  - bdc.bdos.io
  resources:
  - contextsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bdc.bdos.io
  resources:
  - contextsecrets/status
  verbs:
  - get
