apiVersion: bdc.bdos.io/v1alpha1
kind: XDefinition
metadata:
  annotations:
    definition.bdc.bdos.io/description: Init context secret resource
  name: contextsecret-def
spec:
  apiResource:
    definition:
      apiVersion: bdc.bdos.io/v1alpha1
      kind: ContextSecret
      type: default
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "v1"
        	kind:       "Secret"
        	metadata: {
        		name:      context.name
        		namespace: context.namespace
        		annotations: "bdc.bdos.io/name": context.bdcName
        	}
        	type: "Opaque"
        	data: {
            parameter
          }
        }

        parameter: {}
