apiVersion: bdc.bdos.io/v1alpha1
kind: XDefinition
metadata:
  annotations:
    definition.bdc.bdos.io/description: Init custom secret resource
  name: customsecret-def
spec:
  apiResource:
    definition:
      apiVersion: bdc.bdos.io/v1alpha1
      kind: CustomSecret
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "v1"
        	kind:       "Secret"
        	metadata: {
        		name:      parameter.name
        		namespace: context.namespace
        		annotations: "bdc.bdos.io/name": context.bdcName
        	}
        	type: "Opaque"
        	data: parameter.data
        }

        parameter: {
        	// Specify custom secret name
        	name: string
        	// Specify custom secret data
        	data: [string]: string | int | float
        }
