apiVersion: bdc.bdos.io/v1alpha1
kind: XDefinition
metadata:
  annotations:
    definition.bdc.bdos.io/description: Init namespace for bigdatacluster instance
  name: bigdatacluster-def
spec:
  apiResource:
    definition:
      apiVersion: bdc.bdos.io/v1alpha1
      kind: BigDataCluster
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "v1"
        	kind:       "Namespace"
        	metadata: {
        		name: parameter.namespaces[0].name
        		annotations: "bdc.bdos.io/name": context.name
        	}
        }
        outputs: {
        	for i, v in parameter.namespaces {
        		if i > 0 {
        			"objects-\(i)": {
        				apiVersion: "v1"
        				kind:       "Namespace"
        				metadata: {
        					name: v.name
        					annotations: "bdc.bdos.io/name": context.bdcName
        				}
        			}
        		}
        	}
        }

        parameter: {
        	frozen?:   *false | bool
        	disabled?: *false | bool
        	namespaces: [...{
        		name:      string
        		isDefault: bool
        	},
        	]
        }
