apiVersion: bdc.bdos.io/v1alpha1
kind: XDefinition
metadata:
  annotations:
    definition.bdc.bdos.io/description: Init context setting resource
  name: contextsetting-def
spec:
  apiResource:
    definition:
      apiVersion: bdc.bdos.io/v1alpha1
      kind: ContextSetting
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "v1"
        	kind:       "ConfigMap"
        	metadata: {
        		name:      parameter.name
        		namespace: context.namespace
        		annotations: "bdc.bdos.io/name": context.bdcName
        	}
        	data: parameter.data
        }

        parameter: {
        	// Specify context setting name
        	name: string
        	// Specify context setting data
        	data: [string]: string | int | float
        }
